-- [[                    discord.gg/scripts                 ]] --
-- [[                    discord.gg/scripts                 ]] --
-- [[                    discord.gg/scripts                 ]] --
-- [[                    discord.gg/scripts                 ]] --
-- [[                    discord.gg/scripts                 ]] --
-----------------------------------------------------------------
-- [[                   Made By zayy.#7422                  ]] --
-- [[ If u deobf ur a skidder and can't make ur own scripts ]] --
-----------------------------------------------------------------
-- [[                    discord.gg/scripts                 ]] --
-- [[                    discord.gg/scripts                 ]] --
-- [[                    discord.gg/scripts                 ]] --
-- [[                    discord.gg/scripts                 ]] --
-- [[                    discord.gg/scripts                 ]] --
































































































































































_, Protected_by_MoonSecV2, Discord = 'discord.gg/gQEH2uZxUk'


,nil,nil;(function() _msec=(function(e,o,n)local Q=o["        "];local G=n[e[(0x550-701)]][e["        ​        "]];local x=(0x49-69)/((((16553-0x206a)/65)+-#'nicowashere')+-0x72)local i=(((0x32+-54)+-26)+32)-(85/0x55)local z=n[e[(((-#"papier ist ein kleiner schwanz lutscher"+(0xcabe1/51))/0x83)+-#"Crackzzzz")]][e["     ​ ​      "]];local g=(-#"niggers"+((((0xca58/140)-218)+-#"send nudes")-0x86))+(0x67-101)local f=n[e[(517+-#{(function()return#{('BOOOMf'):find("\79")}>0 and 1 or 0 end);1,",",'nil';{};175,175})]][e["          ​     "]]local d=(224/0x70)-(-#[[Lana Rhoades]]+(((18977010/0x39)/0xc5)/130))local t=(5+-#{{},171,(function()return#{('KFhoBH'):find("\104")}>0 and 1 or 0 end)})local w=(63+(-0x18c8/((-#"yeet"+(35+-0x59))+162)))local U=(0x7b+((-#[[testing this thingy lololollez]]+(-0x76+(-#"Lana Rhoades"+(-9408/0xc4))))+87))local b=((55+-#{1,'}','nil';'}'})-0x31)local h=(-#{9,",";(function()return#{('PhBKMm'):find("\66")}>0 and 1 or 0 end)}+5)local O=(-0x2e+(54+-#{(function()return{','}end)(),91,(function()return#{('oLBlMB'):find("\66")}>0 and 1 or 0 end),18;'}';91}))local s=(0x2d/((-0x47+(0x1d+-70))+0x7f))local c=(((0x2fc8-(-0x78+(-#'mike litoris'+(12579-0x18af))))/218)+-#'cilerteddoesntlikeburgers')local k=(0x30-((-#"Ur mom"+((3311+-0x18)-0x6aa))/35))local _=((52+-#{(function()return{','}end)();1,'}';52;52})+-44)local u=(564/(-#{1,(function()return{','}end)(),'nil';1;","}+193))local D=(0x69/(74+(((-#{{};(function()return{','}end)();{};42,'}',1,'nil'}+49)-62)+-#[[how to join the kkk]])))local F=(304/(((0x51cd0/172)+-48)/0x19))local C=((-#[[monkey mode]]+((((-#{(function()return#{('bHbfbp'):find("\98")}>0 and 1 or 0 end),(function()return#{('bHbfbp'):find("\98")}>0 and 1 or 0 end);(function()return{','}end)();(function()return{','}end)()}+15803)/61)+-#"if syn then haxor alert end")-162))-55)local S=(0x30-((0x1aea/((0x501c02/197)/0xcd))+-#[[0nly segc]]))local P=((0x1908/(-#{(function()return{','}end)();13,'nil',(function()return{','}end)()}+13))/0xb2)local y=(0x51+(-15862/(434-(0x8e8/10))))local m=(-#{74;74,92;74}+8)local H=e[(-0x5d+1473)];local I=n[e[(-#"deadphonelua"+(225+-0x62))]][e["           "]];local K=n[(function(e)return type(e):sub(1,1)..'\101\116'end)('   ​    ')..'\109\101'..('\116\97'or'    ​   ')..e[((0x24db/(0x32+-33))+-#"testpsx dupe no scam legit 2022 free no virus")]];local R=n[e[(((144144/0x84)-0x231)+-#"this is a meme string")]][e["​        "]];local p=(0x8c/70)-(-94+((0x14f-(53360/0xe8))+-#[[holy shit]]))local B=((2980/(-#[[big niggers sucking cock]]+(449-((0x252-307)+-#'monkey mode'))))+-#"nico der hurensohn")-((0x55-71)+-#[[deadphonelua]])local j=n[e[((0xd1a0/208)-0x8f)]][e["                  "]];local o=function(o,e)return o..e end local v=(0x3a4/233)*((((4406400/0x88)/162)+-#[[fatee is gay 0nly on top]])/44)local q=n[e["             ​    "]];local r=(396/0xc6)*(0x145-(462-((0x154+(-0x3278/190))+-#'niggers')))local L=(((119214/0x6f)+-20)+-#"testing this thingy lololollez")*(108-((0x4cc86/69)/0x2b))local A=(0x1f7c/(0x9628/((-0x7e+422)+-#'never gonna give you up never gonna let you down')))local N=(0x22/((-125+0xf9)-107))*(0x60+-94)local M=n[e["                "]]or n[e[(-#[[Negro]]+(0xd33b/105))]][e["                "]];local a=((-#'Lana Rhoades'+(44607-((-0x4c+22415)+-#"warboy hates you")))/87)local e=n[e["            "]];local R=(function(a)local r,n=3,0x10 local o={j={},v={}}local l=-d local e=n+i while true do o[a:sub(e,(function()e=r+e return e-i end)())]=(function()l=l+d return l end)()if l==(v-d)then l=""n=p break end end local l=#a while e<l+i do o.v[n]=a:sub(e,(function()e=r+e return e-i end)())n=n+d if n%x==p then n=B R(o.j,(j((o[o.v[B]]*v)+o[o.v[d]])))end end return f(o.j)end)("..:::MoonSec::..                ​   ​                  ​                      ​                     ​                                            ​                 ​                                                         ​         ​ ​                              ​                      ​           ​                        ​             ​        ​                              ​                            ​        ​             ​                     ​  ​                                                      ​                    ​​                           ​       ​ ​                  ​                 ​    ​                              ​                        ​              ​        ​                    ​                                            ​                                      ​   ​                                ​            ​      ​                  ​  ​​                                 ​                    ​   ​              ​        ​​                               ​  ​          ​              ​        ​            ​                        ​                                                    ​    ​                     ​                                   ​       ​            ​  ​             ​                                         ​                ​         ​            ​​       ​                                    ​                           ​                                  ​                                    ​                  ​                  ​  ​     ​          ​                  ​                      ​ ​             ​     ​                       ​                  ​ ​​                                        ​​                ​                                                         ​  ​                   ​                                       ​                    ​                ​    ​                                   ​      ​                   ​            ​          ​                         ​          ​                ​      ​                 ​                                                                 ​                  ​                    ​  ​                                 ​ ​                   ​              ​     ​​                            ​                          ​        ​            ​                    ​              ​                                          ​                      ​  ​          ​                              ​                                     ​                                                    ​  ​                     ​ ​                                                        ​    ​            ​                          ​                                      ​                                                       ​                       ​                       ​                 ​                                                                                  ​         ​           ​      ​​   ​                                             ​    ​           ​                         ​          ​         ​        ​                       ​     ​              ​​                                ​                 ​                     ​                                     ​    ​   ​     ​    ​  ​                  ​​      ​           ​            ​                  ​              ​      ​                                     ​                      ​          ​         ​ ​                        ​          ​            ​                              ​  ​                          ​   ​                             ​               ​             ​     ​  ​                              ​             ​      ​             ​     ​               ​       ​             ​           ​                   ​                   ​​​                                    ​​             ​                     ​​                 ​                      ​           ​     ​             ​                        ​        ​                         ​            ​                ​           ​                    ​              ​           ​       ​                                                               ​​ ​                                                                                               ​               ​                     ​   ​         ​                                            ​                    ​                                    ​    ​                       ​           ​​                                                                        ​           ​                               ​                ​                           ​                          ​                        ​     ​                     ​                        ​             ​                      ​   ​             ​                  ​​    ​    ​                                                   ​          ​                                                                                  ​ ​      ​                     ​                                                          ​   ​            ​​     ​                ​                ​​    ​        ​                        ​​                  ​                    ​                                                          ​               ​ ​         ​       ​       ​             ​    ​                                      ​           ​        ​                   ​    ​                           ​   ​                                       ​              ​               ​​                           ​ ​                        ​                                       ​                   ​  ​              ​                    ​                   ​​       ​         ​​              ​                       ​                                                 ​        ​        ​               ​          ​         ​                  ​                         ​                                                                                            ​                   ​                      ​   ​    ​                           ​​                                                         ​                                                     ​         ​​                                                                                    ​   ​ ​                             ​                 ​                               ​      ​                    ​  ​                                    ​         ​              ​         ​      ​                       ​     ​                            ​      ​       ​    ​                                                                                                       ​​                                                                                 ​ ​                                              ​    ​      ​              ​​      ​                                 ​                             ​                  ​                     ​ ​       ​       ​          ​                ​ ​         ​                    ​   ​                         ​                                     ​         ​                 ​             ​                            ​        ​            ​        ​            ​  ​ ​                                                      ​                   ​                                     ​           ​    ​                    ​    ​                               ​                        ​           ​    ​   ​               ​     ​    ​                                 ​    ​              ​                      ​​     ​                                                    ​                                                 ​       ​             ​           ​      ​                          ​                 ​                ​               ​                    ​  ​                                      ​       ​        ​                      ​  ​                                                     ​​                    ​                                                      ​           ​        ​                    ​    ​ ​          ​        ​               ​                                   ​​     ​                          ​   ​   ​               ​                       ​                                           ​                                   ​                                   ​                           ​        ​            ​                      ​                                     ​                  ​                     ​​    ​                              ​   ​                ​                     ​  ​                                          ​        ​               ​          ​                   ​    ​                                   ​              ​                      ​​ ​                    ​                ​                  ​                   ​​      ​                                                      ");local f=((18300/0x96)+-#[[0nly 1337]])local n=54 local l=d;local e={}e={[(225/0xe1)]=function()local e,i,d,o=z(R,l,l+g);l=l+N;n=(n+(f*N))%a;return(((o+n-(f)+r*(N*x))%r)*((x*L)^x))+(((d+n-(f*x)+r*(x^g))%a)*(r*a))+(((i+n-(f*g)+L)%a)*r)+((e+n-(f*N)+L)%a);end,[(0x68-102)]=function(e,e,e)local e=z(R,l,l);l=l+i;n=(n+(f))%a;return((e+n-(f)+L)%r);end,[(29-0x1a)]=function()local o,e=z(R,l,l+x);n=(n+(f*x))%a;l=l+x;return(((e+n-(f)+r*(x*N))%r)*a)+((o+n-(f*x)+a*(x^g))%r);end,[(-0x62+102)]=function(o,e,n)if n then local e=(o/x^(e-d))%x^((n-i)-(e-d)+i);return e-e%d;else local e=x^(e-i);return(o%(e+e)>=e)and d or B;end;end,[(-#[[elbicho]]+(-16+0x1c))]=function()local o=e[(0x1e+-29)]();local n=e[(109-0x6c)]();local c=d;local l=(e[(-50+0x36)](n,i,v+N)*(x^(v*x)))+o;local o=e[(27-0x17)](n,21,31);local e=((-d)^e[(65-0x3d)](n,32));if(o==B)then if(l==p)then return e*B;else o=i;c=p;end;elseif(o==(r*(x^g))-i)then return(l==B)and(e*(i/p))or(e*(B/p));end;return G(e,o-((a*(N))-d))*(c+(l/(x^A)));end,[(0x33-45)]=function(o,x,x)local x;if(not o)then o=e[(0x22-33)]();if(o==B)then return'';end;end;x=I(R,l,l+o-d);l=l+o;local e=''for o=i,#x do e=H(e,j((z(I(x,o,o))+n)%a))n=(n+f)%r end return e;end}local function R(...)return{...},q('#',...)end local function L()local h={};local l={};local o={};local b={h,l,nil,o};local n={}local w=(0xe79/95)local o={[((693/0x21)+-#[[this is a meme string]])]=(function(o)return not(#o==e[((-0x60+-25)+0x7b)]())end),[(74-0x49)]=(function(o)return e[((-0x79+401)/0x38)]()end),[(0x87/45)]=(function(o)return e[(0x7a-116)]()end),[(-#"free bobux no skem"+(2480/0x7c))]=(function(o)local l=e[(672/0x70)]()local e=''local o=1 for n=1,#l do o=(o+w)%a e=H(e,j((z(l:sub(n,n))+o)%r))end return e end)};for e=i,e[((0x231f/243)-0x24)]()do l[e-i]=L();end;b[3]=e[(0x76-116)]();local l=e[(0x69/105)]()for l=1,l do local e=e[(-#[[deadphonelua]]+(1582/0x71))]();local d;local e=o[e%(0x69-94)];n[l]=e and e({});end;for a=1,e[(0x12+-17)]()do local o=e[(107+(-0x99+48))]();if(e[(-#"fatee is gay 0nly on top"+(0x4d0/44))](o,d,i)==p)then local b=e[(0x56-82)](o,x,g);local l=e[((203-0x93)+-#"If LocalPlayer equals Dumbass then while true do end")](o,N,x+N);local o={e[((0xb9a/99)+-#[[if syn then haxor alert end]])](),e[((0x71+-101)+-#'0nly 1337')](),nil,nil};local r={[(0x0/11)]=function()o[_]=e[(57-0x36)]();o[S]=e[(-0x65+104)]();end,[(0xce/206)]=function()o[_]=e[(-#'Ur mom'+(48-0x29))]();end,[(0xca/101)]=function()o[c]=e[(71+-0x46)]()-(x^v)end,[(-#"send nudes"+(0xbae/(15410/0x43)))]=function()o[s]=e[(((347-0xd2)-0x78)+-#"0nly was here mf")]()-(x^v)o[S]=e[(55+-0x34)]();end};r[b]();if(e[(0x51-77)](l,i,d)==i)then o[U]=n[o[t]]end if(e[((0x624/131)+-#'lego hax')](l,x,x)==d)then o[u]=n[o[k]]end if(e[(-#'howtodumpscript'+(-102+0x79))](l,g,g)==i)then o[S]=n[o[C]]end h[a]=o;end end;return b;end;local function p(e,B,f)local j=e[x];local l=e[g];local a=e[d];return(function(...)local z={};local n=d;local I={};local e=d e*=-1 local N=e;local v=R local R={...};local a=a;local r=l;local l={};local L=q('#',...)-i;local g=j;for e=0,L do if(e>=r)then I[e-r]=R[e+i];else l[e]=R[e+d];end;end;local e=L-r+d local e;local r;while true do e=a[n];r=e[(0xeb/235)];o=(4123168)while r<=(6837/0x9f)do o-= o o=(2241732)while r<=(-68+0x59)do o-= o o=(7214877)while((0x90-129)+-#[[Negro]])>=r do o-= o o=(37383)while r<=(-94+0x62)do o-= o o=(12656923)while((0x9b2/(-#"impulse was here omg"+(0xfa+-84)))+-#[[0nly was here mf]])>=r do o-= o o=(3464009)while(-#[[papier ist ein kleiner schwanz lutscher]]+(-0x77+(-#'elbicho'+(388-0xdf))))<r do o-= o l[e[t]]=(e[_]~=0);break end while 3923==(o)/(((32220/0x24)+-#'deadphonelua'))do local r;local t,x;local o;l[e[b]]=e[s];n=n+d;e=a[n];l[e[O]]=(e[s]~=0);n=n+d;e=a[n];o=e[h]t,x=v(l[o](M(l,o+1,e[c])))N=x+o-1 r=0;for e=o,N do r=r+d;l[e]=t[r];end;n=n+d;e=a[n];o=e[h]l[o]=l[o](M(l,o+d,N))n=n+d;e=a[n];l[e[w]]();n=n+d;e=a[n];l[e[b]]=f[e[D]];n=n+d;e=a[n];l[e[w]]=e[c];n=n+d;e=a[n];l[e[U]]=e[c];n=n+d;e=a[n];l[e[b]]=e[c];n=n+d;e=a[n];o=e[w]l[o](M(l,o+i,e[s]))break end;break;end while(o)/((4032+-0x49))==3197 do o=(5984544)while r<=((351/0x27)+-#"elbicho")do o-= o l[e[U]]=p(g[e[D]],nil,f);break;end while(o)/((-#[[monkey mode]]+(507286/0xda)))==2584 do o=(7008981)while r>(180/0x3c)do o-= o local o=e[b];local d=l[o]local a=l[o+2];if(a>0)then if(d>l[o+1])then n=e[k];else l[o+3]=d;end elseif(d<l[o+1])then n=e[c];else l[o+3]=d;end break end while(o)/((3477+-0x1a))==2031 do l[e[U]]=l[e[_]][l[e[C]]];break end;break;end break;end break;end while 2199==(o)/(((0x4d+-48)+-#[[deadphonelua]]))do o=(658350)while r<=(-85+(0xd7-123))do o-= o o=(471706)while(0x5/1)>=r do o-= o do return l[e[U]]end break;end while 2078==(o)/((-98+0x145))do o=(9334926)while(0x64-94)<r do o-= o B[e[s]]=l[e[O]];break end while 2349==(o)/((0x1f6a-4068))do l[e[w]]=l[e[k]][e[P]];break end;break;end break;end while 330==(o)/(((186651/0x5d)+-#'cilertedcool'))do o=(1369851)while((0x44-45)+-#[[howtodumpscript]])>=r do o-= o local o=e[b]l[o]=l[o](M(l,o+d,e[u]))break;end while 1591==(o)/((0x6f2-917))do o=(1213970)while r>(0x44+-59)do o-= o local e=e[t]l[e]=l[e]()break end while(o)/((3979-0x801))==629 do local e=e[w]l[e]=l[e](M(l,e+d,N))break end;break;end break;end break;end break;end while 2297==(o)/((0x80103/(-#[[cruz pp is large]]+(285+-0x66))))do o=(1995532)while(780/0x34)>=r do o-= o o=(863200)while r<=(-#'If LocalPlayer equals Dumbass then while true do end'+(5760/0x5a))do o-= o o=(15021108)while r>(869/0x4f)do o-= o l[e[b]]=B[e[c]];break end while 4051==(o)/((0x1d73-3831))do if(l[e[t]]==e[F])then n=n+i;else n=e[u];end;break end;break;end while 2075==(o)/((101504/(-0x73+359)))do o=(6437200)while r<=((147-0x6e)+-#'0nly 1337 smashed ur wap')do o-= o local o=e[h]l[o](M(l,o+i,e[D]))break;end while(o)/(((0xd58+-53)+-#'how to join the kkk'))==1925 do o=(451122)while r>((114-0x5f)+-#[[Negro]])do o-= o local o=e[t]l[o]=l[o](M(l,o+d,e[u]))break end while 161==(o)/(((-0x31+2866)+-#[[howtodumpscript]]))do l[e[t]]=B[e[s]];break end;break;end break;end break;end while(o)/((0x4e8+-78))==1694 do o=(4207728)while r<=((660/(-#[[send nudes]]+(0x64-80)))+-#[[never gonna give you up never gonna let you down]])do o-= o o=(1915920)while(0x7a+-106)>=r do o-= o if(l[e[O]]==l[e[P]])then n=n+i;else n=e[k];end;break;end while 2160==(o)/((1854-0x3c7))do o=(1367290)while r>(0x64-(0xf1-158))do o-= o n=e[k];break end while 3746==(o)/((-55+0x1a4))do l[e[U]][l[e[s]]]=l[e[S]];break end;break;end break;end while(o)/(((0x4b82b/131)+-#'holy shit'))==1789 do o=(5370786)while(-#"0nly 1337"+(6188/(0x158+-123)))>=r do o-= o l[e[O]][l[e[D]]]=l[e[P]];break;end while(o)/((-#'Fucking losed 027728272728271'+(0x5e5a2/246)))==3483 do o=(364656)while((209-0x96)+-#[[papier ist ein kleiner schwanz lutscher]])<r do o-= o local o;f[e[s]]=l[e[b]];n=n+d;e=a[n];l[e[b]]=f[e[c]];n=n+d;e=a[n];o=e[h]l[o]=l[o]()n=n+d;e=a[n];l[e[b]]=f[e[u]];n=n+d;e=a[n];l[e[b]]=l[e[u]][e[C]];n=n+d;e=a[n];l[e[t]]=l[e[D]][e[m]];n=n+d;e=a[n];l[e[h]]=l[e[u]][e[C]];n=n+d;e=a[n];l[e[O]][e[D]]=l[e[y]];n=n+d;e=a[n];l[e[b]]=f[e[c]];n=n+d;e=a[n];l[e[b]]=f[e[u]];break end while 142==(o)/((5158-0xa1e))do l[e[w]]=(e[s]~=0);break end;break;end break;end break;end break;end break;end while(o)/((2163-0x447))==2099 do o=(116518)while r<=(3360/0x69)do o-= o o=(7265280)while((126-0x54)+-#"warboy hates you")>=r do o-= o o=(6219976)while((-0x40+98)+-#"nicowashere")>=r do o-= o o=(9407000)while r>(5104/0xe8)do o-= o l[e[b]]=f[e[c]];break end while(o)/((0x779ac/213))==4090 do l[e[h]]=l[e[D]]%e[P];break end;break;end while 2038==(o)/((390656/0x80))do o=(13264755)while r<=(80-0x38)do o-= o local e=e[U]l[e]=l[e](l[e+i])break;end while(o)/((-#'this is a meme string'+(0x1e47-3915)))==3477 do o=(4547400)while r>(75-0x32)do o-= o l[e[w]]=e[_];break end while 2915==(o)/((-#'impulse was here omg'+(0x66f+-67)))do l[e[t]]();break end;break;end break;end break;end while(o)/(((571200/0xc8)+-#'nico der hurensohn'))==2560 do o=(8984121)while r<=(125+-0x60)do o-= o o=(5000127)while r<=(0x1584/204)do o-= o l[e[h]]=f[e[_]];break;end while(o)/((72204/0x2c))==3047 do o=(1019205)while r>(6300/0xe1)do o-= o local r;local w,t;local x;local o;l[e[b]]=f[e[k]];n=n+d;e=a[n];o=e[U];x=l[e[c]];l[o+1]=x;l[o]=x[e[m]];n=n+d;e=a[n];l[e[b]]=e[_];n=n+d;e=a[n];l[e[h]]=(e[s]~=0);n=n+d;e=a[n];o=e[U]w,t=v(l[o](M(l,o+1,e[k])))N=t+o-1 r=0;for e=o,N do r=r+d;l[e]=w[r];end;n=n+d;e=a[n];o=e[h]l[o]=l[o](M(l,o+d,N))n=n+d;e=a[n];l[e[b]]();n=n+d;e=a[n];l[e[h]]=f[e[k]];n=n+d;e=a[n];l[e[O]]=e[_];n=n+d;e=a[n];o=e[h]l[o](l[o+i])break end while 355==(o)/(((736185/0xff)+-#"0nly was here mf"))do l[e[w]]=l[e[k]]%e[P];break end;break;end break;end while(o)/((((-#[[cruz pp is large]]+(0x1fee+-112))-4071)+-#[[mike litoris]]))==2267 do o=(6500766)while((0x64-65)+-#'Negro')>=r do o-= o local o;l[e[w]]=e[s];n=n+d;e=a[n];o=e[w]l[o](l[o+i])n=n+d;e=a[n];l[e[w]]=f[e[u]];n=n+d;e=a[n];l[e[w]]=e[u];n=n+d;e=a[n];l[e[b]]=e[s];n=n+d;e=a[n];l[e[U]]=e[u];n=n+d;e=a[n];o=e[t]l[o](M(l,o+i,e[k]))n=n+d;e=a[n];l[e[h]]=f[e[c]];n=n+d;e=a[n];l[e[t]]=e[D];n=n+d;e=a[n];o=e[w]l[o](l[o+i])break;end while(o)/((-#'cilerteddoesntlikeburgers'+(-49+0x710)))==3749 do o=(9805840)while r>(-#"0nly was here mf"+(90+-0x2b))do o-= o l[e[t]]=l[e[D]];break end while(o)/((-124+0x1050))==2420 do if l[e[U]]then n=n+d;else n=e[u];end;break end;break;end break;end break;end break;end while 3427==(o)/(((0x115-192)-0x33))do o=(300160)while(2516/0x44)>=r do o-= o o=(5061420)while r<=((11408/0xf8)+-#[[cilertedcool]])do o-= o o=(496888)while((155+-0x6a)+-#"Fucking Retarted")<r do o-= o local o=e[O]l[o](M(l,o+i,e[k]))break end while(o)/((-#"If LocalPlayer equals Dumbass then while true do end"+(((0x1c47b07/117)+-#[[nicowashere]])/132)))==266 do local e={l,e};e[i][e[x][h]]=e[d][e[x][y]]+e[i][e[x][k]];break end;break;end while 1545==(o)/((-#"nicowashere"+(0xb2f49/223)))do o=(5874102)while(0xbc2/86)>=r do o-= o l[e[t]]=l[e[u]][e[y]];break;end while(o)/((0x19fe6/35))==1931 do o=(3634840)while r>(-#[[big niggers sucking cock]]+(0x31ec/213))do o-= o local o=e[O]local n,e=v(l[o](M(l,o+1,e[c])))N=e+o-1 local e=0;for o=o,N do e=e+d;l[o]=n[e];end;break end while 3004==(o)/((0x14adc/70))do l[e[t]]=l[e[D]];break end;break;end break;end break;end while(o)/((596568/0x9f))==80 do o=(980274)while r<=((0x35ca/(1134/0x7))+-#"testpsx dupe no scam legit 2022 free no virus")do o-= o o=(1266507)while(0x1326/129)>=r do o-= o if(l[e[b]]~=l[e[m]])then n=n+i;else n=e[_];end;break;end while 363==(o)/(((-0x53+3584)+-#'mike litoris'))do o=(12810860)while(0x52+-43)<r do o-= o l[e[O]][e[k]]=e[C];break end while 3485==(o)/(((-0x19ec/158)+3718))do local r;local o;l[e[h]]=e[s];n=n+d;e=a[n];l[e[U]]=e[c];n=n+d;e=a[n];o=e[t]l[o](M(l,o+i,e[u]))n=n+d;e=a[n];l[e[t]]=f[e[_]];n=n+d;e=a[n];l[e[O]]=e[s];n=n+d;e=a[n];o=e[b]l[o](l[o+i])n=n+d;e=a[n];o=e[O];r=l[e[c]];l[o+1]=r;l[o]=r[e[S]];n=n+d;e=a[n];l[e[U]]=e[s];n=n+d;e=a[n];o=e[t]l[o](M(l,o+i,e[s]))n=n+d;e=a[n];l[e[t]]=f[e[s]];break end;break;end break;end while(o)/((1740+-0x62))==597 do o=(450750)while r<=(0x1004/100)do o-= o local n=e[w];local o=l[e[c]];l[n+1]=o;l[n]=o[e[C]];break;end while(o)/((-17+0xe27))==125 do o=(2444532)while(0xab-129)<r do o-= o local i;local r;local o;l[e[w]]=e[c];n=n+d;e=a[n];l[e[t]]=e[s];n=n+d;e=a[n];l[e[U]]=#l[e[k]];n=n+d;e=a[n];l[e[O]]=e[c];n=n+d;e=a[n];o=e[w];r=l[o]i=l[o+2];if(i>0)then if(r>l[o+1])then n=e[D];else l[o+3]=r;end elseif(r<l[o+1])then n=e[D];else l[o+3]=r;end break end while 2084==(o)/((14076/0xc))do local o=e[U];local a=l[o+2];local d=l[o]+a;l[o]=d;if(a>0)then if(d<=l[o+1])then n=e[s];l[o+3]=d;end elseif(d>=l[o+1])then n=e[D];l[o+3]=d;end break end;break;end break;end break;end break;end break;end break;end while 3728==(o)/((-45+0x47f))do o=(2691920)while r<=((258-0xb1)+-#[[Fucking Retarted]])do o-= o o=(7376064)while(166-0x70)>=r do o-= o o=(7412580)while(-#"Impulse youtube real"+(0xc4-128))>=r do o-= o o=(5836215)while(175-0x82)>=r do o-= o o=(8077002)while((152+-0x42)+-42)<r do o-= o local o=e[h];local a=l[o+2];local d=l[o]+a;l[o]=d;if(a>0)then if(d<=l[o+1])then n=e[D];l[o+3]=d;end elseif(d>=l[o+1])then n=e[_];l[o+3]=d;end break end while 3282==(o)/((-#'testpsx dupe no scam legit 2022 free no virus'+(2541+-0x23)))do l[e[w]]=l[e[D]]-l[e[m]];break end;break;end while 3255==(o)/((3709-0x77c))do o=(3830856)while r<=(-#"nicowashere"+(-47+0x68))do o-= o local n=e[h];local o=l[e[k]];l[n+1]=o;l[n]=o[e[P]];break;end while(o)/((-#[[keno 0347 is a nerdy fag]]+(24906/0x7)))==1084 do o=(652310)while(-#"big niggers sucking cock"+(174-0x67))<r do o-= o local r=g[e[u]];local d;local o={};d=K({},{__index=function(n,e)local e=o[e];return e[1][e[2]];end,__newindex=function(l,e,n)local e=o[e]e[1][e[2]]=n;end;});for d=1,e[C]do n=n+i;local e=a[n];if e[(23+-0x16)]==36 then o[d-1]={l,e[k]};else o[d-1]={B,e[c]};end;z[#z+1]=o;end;l[e[U]]=p(r,d,f);break end while 370==(o)/((-#'monkey mode'+(-0x38+1830)))do B[e[_]]=l[e[h]];break end;break;end break;end break;end while 2862==(o)/((0xa4c+-46))do o=(3430448)while(153-0x66)>=r do o-= o o=(656754)while r<=((0xea-140)+-#"testpsx dupe no scam legit 2022 free no virus")do o-= o l[e[U]]=e[c];break;end while(o)/((5053-0xa18))==266 do o=(3938073)while(5000/0x64)<r do o-= o l[e[b]]={};break end while 3363==(o)/((0x984-1265))do f[e[u]]=l[e[h]];break end;break;end break;end while(o)/((-0x12+3952))==872 do o=(696320)while r<=(177+-0x7d)do o-= o l[e[h]]();break;end while(o)/((-#'Lana Rhoades'+(0x4353c/201)))==512 do o=(6622155)while r>(129-0x4c)do o-= o n=e[_];break end while(o)/((0x71fbb/125))==1773 do local B;local r;local N;local o;l[e[U]]=f[e[c]];n=n+d;e=a[n];l[e[O]]=l[e[_]][e[m]];n=n+d;e=a[n];o=e[w];N=l[e[u]];l[o+1]=N;l[o]=N[e[P]];n=n+d;e=a[n];l[e[U]]=l[e[s]];n=n+d;e=a[n];l[e[h]]=l[e[k]];n=n+d;e=a[n];o=e[U]l[o]=l[o](M(l,o+d,e[k]))n=n+d;e=a[n];o=e[O];N=l[e[s]];l[o+1]=N;l[o]=N[e[y]];n=n+d;e=a[n];o=e[t]l[o]=l[o](l[o+i])n=n+d;e=a[n];r={l,e};r[i][r[x][w]]=r[d][r[x][P]]+r[i][r[x][D]];n=n+d;e=a[n];l[e[b]]=l[e[c]]%e[F];n=n+d;e=a[n];o=e[t]l[o]=l[o](l[o+i])n=n+d;e=a[n];N=e[_];B=l[N]for e=N+1,e[S]do B=B..l[e];end;l[e[b]]=B;n=n+d;e=a[n];r={l,e};r[i][r[x][h]]=r[d][r[x][m]]+r[i][r[x][u]];n=n+d;e=a[n];l[e[O]]=l[e[s]]%e[P];break end;break;end break;end break;end break;end while(o)/((0xf8e-2014))==3748 do o=(1134400)while(-#[[Lana Rhoades]]+(0x101-186))>=r do o-= o o=(687227)while(-#"nicowashere"+(0xe9-166))>=r do o-= o o=(2675260)while r>(167-0x70)do o-= o l[e[w]][e[s]]=l[e[m]];break end while(o)/((-#"cilertedcool"+(6851-0xd74)))==788 do local e=e[w]l[e]=l[e](M(l,e+d,N))break end;break;end while(o)/((-#"testpsx dupe no scam legit 2022 free no virus"+(0x9c00/156)))==3257 do o=(12421588)while r<=(0x1cb9/129)do o-= o local e=e[b]l[e](l[e+i])break;end while(o)/((-#[[send nudes]]+(0x6aca8/107)))==3046 do o=(220287)while(0x3008/212)<r do o-= o l[e[w]]=l[e[c]]-l[e[P]];break end while 97==(o)/((4650-0x94b))do l[e[O]]=#l[e[k]];break end;break;end break;end break;end while(o)/((0xafdd8/254))==400 do o=(5623740)while r<=((286-0xcd)+-#'how to join the kkk')do o-= o o=(11229036)while(0xe8-172)>=r do o-= o f[e[_]]=l[e[O]];break;end while 2938==(o)/((-50+0xf20))do o=(503875)while(-#"deadphonelua"+(-34+0x6b))<r do o-= o if(l[e[b]]==l[e[y]])then n=n+i;else n=e[_];end;break end while 3475==(o)/((320-0xaf))do local o=e[t]local n,e=v(l[o](M(l,o+1,e[u])))N=e+o-1 local e=0;for o=o,N do e=e+d;l[o]=n[e];end;break end;break;end break;end while(o)/((364240/0x74))==1791 do o=(2080696)while(0x87+(-#'If LocalPlayer equals Dumbass then while true do end'+(-0x1-19)))>=r do o-= o local r;local o;l[e[U]]=B[e[c]];n=n+d;e=a[n];o=e[O];r=l[e[u]];l[o+1]=r;l[o]=r[e[y]];n=n+d;e=a[n];l[e[t]]=e[c];n=n+d;e=a[n];l[e[O]]={};n=n+d;e=a[n];l[e[O]][e[c]]=l[e[C]];n=n+d;e=a[n];l[e[h]][e[u]]=l[e[C]];n=n+d;e=a[n];l[e[t]][e[c]]=l[e[P]];n=n+d;e=a[n];l[e[w]][e[k]]=e[y];n=n+d;e=a[n];o=e[t]l[o](M(l,o+i,e[_]))n=n+d;e=a[n];do return end;break;end while 1432==(o)/(((0x61e+-102)+-#[[nicowashere]]))do o=(1203576)while r>(242-0xb2)do o-= o l[e[b]]=#l[e[k]];break end while 1551==(o)/((1679-0x387))do l[e[h]]={};break end;break;end break;end break;end break;end break;end while 3496==(o)/((49280/0x40))do o=(2000700)while(-#[[nerd]]+(0x3200/160))>=r do o-= o o=(9504190)while((-0x33+129)+-#[[lego hax]])>=r do o-= o o=(3153024)while r<=(-#'lego hax'+(0xbb8/40))do o-= o o=(974448)while(171+-0x69)<r do o-= o local e=e[O]l[e]=l[e](l[e+i])break end while 1818==(o)/((0x15330/162))do local e=e[t]l[e]=l[e]()break end;break;end while(o)/(((293760/0xd8)+-#"warboy hates you"))==2346 do o=(7216846)while r<=(-#"0nly 1337 smashed ur wap"+(220-0x80))do o-= o l[e[h]][e[u]]=l[e[P]];break;end while 2087==(o)/((0xe01+-127))do o=(981090)while r>(-#[[Niggabyte]]+(0xea0/48))do o-= o l[e[t]]=(e[D]~=0);n=n+i;break end while 1982==(o)/((53955/0x6d))do if(l[e[U]]~=l[e[y]])then n=n+i;else n=e[k];end;break end;break;end break;end break;end while(o)/((3063+-0x29))==3145 do o=(1485078)while(0xa4+-91)>=r do o-= o o=(9265920)while(261-0xbe)>=r do o-= o do return end;break;end while 3840==(o)/((0x67af0/176))do o=(92400)while r>((0xe5-148)+-#'0nly segc')do o-= o local n=e[c];local o=l[n]for e=n+1,e[S]do o=o..l[e];end;l[e[w]]=o;break end while(o)/((4620/0x6e))==2200 do l[e[w]]=B[e[_]];n=n+d;e=a[n];l[e[U]]=#l[e[u]];n=n+d;e=a[n];B[e[u]]=l[e[h]];n=n+d;e=a[n];l[e[O]]=B[e[D]];n=n+d;e=a[n];l[e[w]]=#l[e[u]];n=n+d;e=a[n];B[e[u]]=l[e[w]];n=n+d;e=a[n];do return end;break end;break;end break;end while(o)/((55062/0x45))==1861 do o=(3462930)while r<=(178-0x68)do o-= o l[e[O]]=l[e[D]][l[e[m]]];break;end while(o)/(((2232+-0x4b)+-#[[papier ist ein kleiner schwanz lutscher]]))==1635 do o=(8876368)while r>(0x3d86/210)do o-= o local n=e[D];local o=l[n]for e=n+1,e[P]do o=o..l[e];end;l[e[b]]=o;break end while 3728==(o)/((0x851e1/229))do f[e[_]]=l[e[b]];n=n+d;e=a[n];l[e[O]]={};n=n+d;e=a[n];l[e[h]]={};n=n+d;e=a[n];f[e[k]]=l[e[h]];n=n+d;e=a[n];l[e[h]]=f[e[c]];n=n+d;e=a[n];if(l[e[h]]==e[P])then n=n+i;else n=e[s];end;break end;break;end break;end break;end break;end while 2340==(o)/((-#'mf stfu'+(0x72f-977)))do o=(328208)while((0x108-158)+-#'keno 0347 is a nerdy fag')>=r do o-= o o=(2269575)while(0x382a/182)>=r do o-= o o=(2402550)while(-107+0xb8)>=r do o-= o local e=e[w]l[e](l[e+i])break;end while 2529==(o)/((-#[[0nly segc]]+(2038-0x437)))do o=(2201385)while(-#'nerd'+(279-0xc5))<r do o-= o do return l[e[b]]end break end while(o)/((0x2fa+-117))==3413 do if l[e[b]]then n=n+d;else n=e[c];end;break end;break;end break;end while 2751==(o)/((-0x3f+888))do o=(2054364)while r<=(-0x61+177)do o-= o do return end;break;end while 3039==(o)/((0x5b8-(106380/0x87)))do o=(1329624)while r>(0x2d9/9)do o-= o l[e[h]][e[D]]=e[S];break end while 2504==(o)/((1109-0x242))do local o=e[t];local d=l[o]local a=l[o+2];if(a>0)then if(d>l[o+1])then n=e[u];else l[o+3]=d;end elseif(d<l[o+1])then n=e[c];else l[o+3]=d;end break end;break;end break;end break;end while(o)/((0x2082/57))==2248 do o=(6917664)while(-#"nerd"+(-0x50+169))>=r do o-= o o=(2334996)while r<=(-0x75+200)do o-= o if(l[e[w]]==e[S])then n=n+i;else n=e[u];end;break;end while(o)/((-#"send nudes"+(-0x16+1364)))==1753 do o=(2326836)while r>(0xc3+-111)do o-= o l[e[t]]=p(g[e[_]],nil,f);break end while(o)/(((988494/0xf7)+-#'yeet'))==582 do local r=g[e[_]];local d;local o={};d=K({},{__index=function(n,e)local e=o[e];return e[1][e[2]];end,__newindex=function(l,e,n)local e=o[e]e[1][e[2]]=n;end;});for d=1,e[C]do n=n+i;local e=a[n];if e[(0x73-114)]==36 then o[d-1]={l,e[k]};else o[d-1]={B,e[c]};end;z[#z+1]=o;end;l[e[O]]=p(r,d,f);break end;break;end break;end while 2208==(o)/((6380-0xcaf))do o=(10539742)while r<=(197-(190+-0x4f))do o-= o local e={l,e};e[i][e[x][t]]=e[d][e[x][S]]+e[i][e[x][k]];break;end while(o)/(((0x19ff-3346)+-#'papier der afghaner wurde von nice dem bombenleger gefickt'))==3242 do o=(13099616)while r>((0x924/20)+-#"testing this thingy lololollez")do o-= o l[e[h]]=(e[_]~=0);n=n+i;break end while 3352==(o)/(((-0x37+578439)/0x94))do local r;local o;f[e[D]]=l[e[b]];n=n+d;e=a[n];l[e[O]]=f[e[c]];n=n+d;e=a[n];l[e[O]]=l[e[k]][e[P]];n=n+d;e=a[n];l[e[h]]=l[e[k]][e[F]];n=n+d;e=a[n];l[e[t]]=f[e[c]];n=n+d;e=a[n];o=e[h];r=l[e[k]];l[o+1]=r;l[o]=r[e[C]];n=n+d;e=a[n];l[e[t]]=e[D];n=n+d;e=a[n];o=e[U]l[o]=l[o](M(l,o+d,e[k]))break end;break;end break;end break;end break;end break;end break;end n+= i end;end);end;return p(L(),{},Q())()end)_msec({[(15640/0x88)]='\115\116'..(function(e)return(e and'              ')or'\114\105'or'\120\58'end)((94-0x59)==(0x264/(-0x37+157)))..'\110g',["        ​        "]='\108\100'..(function(e)return(e and'             ​​')or'\101\120'or'\119\111'end)((270/0x36)==(-0x26+44))..'\112',["     ​ ​      "]=(function(e)return(e and'    ​          ')and'\98\121'or'\100\120'end)((-#[[nico der hurensohn]]+(46/0x2))==((-#"Lana Rhoades"+(-3588/0x5c))+56))..'\116\101',["                  "]='\99'..(function(e)return(e and'   ​  ​  ​   ​')and'\90\19\157'or'\104\97'end)((0x6c-103)==(-#'Fucking Retarted'+(4712/0xf8)))..'\114',[(((0x8ba-1135)-0x22f)+-#'testing this thingy lololollez')]='\116\97'..(function(e)return(e and'             ')and'\64\113'or'\98\108'end)((-#'mike litoris'+(0x78-102))==(0x39+-52))..'\101',["           "]=(function(e)return(e and'              ')or'\115\117'or'\78\107'end)((0x21-30)==(-0x2b+74))..'\98',["          ​     "]='\99\111'..(function(e)return(e and'           ')and'\110\99'or'\110\105\103\97'end)((138-0x6b)==(138-0x6b))..'\97\116',[(-86+0x2e9)]=(function(e,o)return(e and'          ')and'\48\159\158\188\10'or'\109\97'end)((-#"big niggers sucking cock"+(0x12eb/167))==((0x79e/65)+-#'big niggers sucking cock'))..'\116\104',[((-0x5b+1483)+-#'cilertedcool')]=(function(o,e)return(((-107+0x4d)+35)==(((14-0x3a)+0x36)+-#'mf stfu')and'\48'..'\195'or o..((not'\20\95\69'and'\90'..'\180'or e)))or'\199\203\95'end),["​        "]='\105\110'..(function(e,o)return(e and'           ​')and'\90\115\138\115\15'or'\115\101'end)((83-(0xe7-153))==(0x64-69))..'\114\116',["                "]='\117\110'..(function(e,o)return(e and'         ')or'\112\97'or'\20\38\154'end)(((-0x7f+225)+-0x5d)==((-88+0xb9)-0x42))..'\99\107',["             ​    "]='\115\101'..(function(e)return(e and'     ​ ​ ​  ​  ')and'\110\112\99\104'or'\108\101'end)((0x3e-57)==(-111+0x8e))..'\99\116',["            "]='\116\111\110'..(function(e,o)return(e and'    ​           ')and'\117\109\98'or'\100\97\120\122'end)((75+-0x46)==(0x19f/83))..'\101\114'},{["        "]=((getfenv))},((getfenv))()) end)()


